services:
  mongodb:
    image: mongo:7.0
    container_name: sightsearch-mongodb
    ports:
      - "27020:27017"
    volumes:
      - mongo-data:/data/db

  postgres:
    image: postgres:15
    container_name: sightsearch-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5438:5432"

  scraper:
    build:
      context: ..
      dockerfile: docker/scraper/Dockerfile
    container_name: sightsearch-scraper
    environment:
      - IMAGE_DIR=/app/images
      - MONGO_URI=mongodb://mongodb:27017/sightsearch
    volumes:
      - ../images:/app/images
    depends_on:
      - mongodb
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: "no"

  airflow-init:
    image: apache/airflow:3.1.6
    container_name: sightsearch-airflow-init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        pip install --no-cache-dir apache-airflow-providers-fab
        airflow db migrate
        airflow db reset -y
        airflow db migrate
        airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
      AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    depends_on:
      - postgres
    volumes:
      - airflow-db:/opt/airflow
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ../src:/opt/airflow/src 

  airflow-webserver:
    image: apache/airflow:3.1.6
    container_name: sightsearch-airflow-webserver
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    entrypoint: /bin/bash
    command:
      - -c
      - |
        pip install --no-cache-dir apache-airflow-providers-fab
        airflow api-server
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
      AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    ports:
      - "8080:8080"
    volumes:
      - airflow-db:/opt/airflow
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ../src:/opt/airflow/src 

  airflow-scheduler:
    image: apache/airflow:3.1.6
    container_name: sightsearch-airflow-scheduler
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    entrypoint: /bin/bash
    command:
      - -c
      - |
        pip install --no-cache-dir apache-airflow-providers-fab
        airflow scheduler
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
      AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
      - airflow-db:/opt/airflow
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ../src:/opt/airflow/src 

volumes:
  mongo-data:
  airflow-db:
  postgres-data: