services:
  scraper:
    build:
      context: ..
      dockerfile: docker/scraper/Dockerfile
    container_name: sightsearch-scraper
    volumes:
      - ../images:/app/images
    environment:
      - IMAGE_DIR=/app/images
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: "no"

  mongodb:
    image: mongo:7.0
    container_name: sightsearch-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: