services:
  scraper:
    build:
      context: ..
      dockerfile: docker/scraper/Dockerfile
    container_name: sightsearch-scraper
    environment:
      - IMAGE_DIR=/app/images
      - MONGO_URI=mongodb://mongodb:27017/sightsearch
    volumes:
      - ../images:/app/images
    depends_on:
      - mongodb
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: "no"

  mongodb:
    image: mongo:7.0
    container_name: sightsearch-mongodb
    ports:
      - "27020:27017"
    volumes:
      - mongo-data:/data/db

  # Airflow Scheduler
  airflow-scheduler:
    image: apache/airflow:3.0.2
    container_name: sightsearch-airflow-scheduler
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.no_auth"
    volumes:
      - airflow-db:/opt/airflow
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    command: scheduler
    depends_on:
      - airflow-webserver

  airflow-webserver:
    image: apache/airflow:3.0.2
    container_name: sightsearch-airflow-webserver
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__WEBSERVER__AUTHENTICATE: "False"
      AIRFLOW__WEBSERVER__RBAC: "False"
    volumes:
      - airflow-db:/opt/airflow
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    command: webserver
    ports:
      - "8080:8080"
    depends_on:
      - airflow-scheduler


volumes:
  mongo-data:
  airflow-db: