services:
  mongodb:
    image: mongo:7.0
    container_name: sightsearch-mongodb
    ports:
      - "27020:27017"
    volumes:
      - mongo-data:/data/db

  postgres:
    image: postgres:15
    container_name: sightsearch-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5438:5432"

  scraper:
    build:
      context: ..
      dockerfile: docker/scraper/Dockerfile
    container_name: sightsearch-scraper
    environment:
      - IMAGE_DIR=/app/images
      - MONGO_URI=mongodb://mongodb:27017/sightsearch
    volumes:
      - ../images:/app/images
    depends_on:
      - mongodb
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: "no"

  airflow-init:
    image: apache/airflow:3.0.6
    container_name: sightsearch-airflow-init
    entrypoint: /bin/sh
    command: >
      -c "sleep 6 \
      && airflow db migrate \
      || true"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__WEBSERVER__RBAC: "False"
    depends_on:
      - postgres
    volumes:
      - airflow-db:/opt/airflow
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow-init.py:/opt/airflow/airflow-init.py

  airflow-webserver:
    image: apache/airflow:3.0.6
    container_name: sightsearch-airflow-webserver
    restart: always
    depends_on:
      - airflow-init
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__WEBSERVER__AUTH_BACKEND: airflow.auth.backends.webserver.NoAuth
    command: api-server
    ports:
      - "8080:8080"
    volumes:
      - airflow-db:/opt/airflow
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins

  airflow-scheduler:
    image: apache/airflow:3.0.6
    container_name: sightsearch-airflow-scheduler
    restart: always
    depends_on:
      - airflow-webserver
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__WEBSERVER__RBAC: "False"
    command: scheduler
    volumes:
      - airflow-db:/opt/airflow
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins

volumes:
  mongo-data:
  airflow-db:
  postgres-data: